### ISSUE TITLE
Slider handles do not work inside px-modal with Firefox

### ISSUE THREAD

**Issue by alump** [PredixDev/px-slider#29]
Looks like px-modal breaks some mouse event handling of px-slider with Firefox. User can not drag handles (they just jump to edges).

Simple code to reproduce the issues (happens at least on pages without theming rules):
https://gist.github.com/alump/2d1d4d427f0f20f8ea9b772d415962fb

Will attach code also as comment below.

Just copy-paste somewhere where px-modal and px-slider are available. And try with Firefox.

**Comment by alump** [comment]
```html
  <px-modal
    header-text="Confirm delete"
    body-text="Do you want to delete this record? The record will be deleted permanently."
    accept-text="Permanently Delete Record"
    reject-text="Cancel"
    open-trigger="[[trigger]]">
    <div slot="body">
      <px-slider
      value="10"
      end-value="90"
      min="0"
      max="100"
      step="1"
      is-range
      scale="linear"
      base="10"
      exponent="2"
      min-label-position="bottom"
      max-label-position="bottom">
      </px-slider>
    </div>
  </px-modal>
  <px-modal-trigger
    trigger='{{trigger}}'>
    <button
      class='btn btn--tertiary'>Open Modal
    </button>
  </px-modal-trigger>
```

**Comment by nonmetalhail** [comment]
Related to: [https://github.com/d3/d3/issues/2771](https://github.com/d3/d3/issues/2771)

**Comment by nonmetalhail** [comment]
Related to: d3/d3#2771

**Comment by nonmetalhail** [comment]
Adding a bit more description here for future reference:

This is due to a long standing Firefox bug with `getScreenCTM` (which d3 uses under the hood) and there is no graceful alternative. Firefox `getScreenCTM` returns the wrong values for SVG elems that are in a HTML element with a `transform` on them. 

The "fix" in the PR BASICALLY searches for ancestor elements which have a `transform`, adds up the transformations, and attempts to correct the misreported values. This works fine for `translate`, though other transforms could very well break it. 

If Mozilla ever gets around to fixing this bug, that will also cause the slider to break in similar fashion and the added code will need to be removed.
